version: '3'
services:
  web:
    container_name: web_bs
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - "./devops/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./devops/nginx/conf.d:/etc/nginx/conf.d"
      - "./:/var/www/html"
    depends_on:
      - php
    networks:
      - bs
    command: [nginx-debug, '-g', 'daemon off;']

  php:
    image: php:7.3-fpm
    expose:
      - 9000
#    ports:
#      - "9000:9000"
    container_name: php_bs
    volumes:
      - "./:/var/www/html"
    networks:
      - bs
  db:
    container_name: db_bs
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./db/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=battle
networks:
  bs:
    driver: bridge
volumes:
  web_app:
